---
- name: Spring Boot
  hosts: "{{ target | default('localhost') }}"
  become: yes
  roles:
  - { role: ansible-springboot-role, 
      spring_boot_file_source_local: 'bootrest/target/bootrest-1.jar' 
    }
