- name: "Copy jar application"
  copy:
    remote_src: True
    src: "{{ spring_boot_file }}"
    dest: "{{ spring_boot_user_dir }}/{{ spring_boot_application_id }}.jar"
    owner: "{{ spring_boot_username }}"
    group: "{{ spring_boot_username }}"
    mode: "u+x"
  when: spring_boot_file is defined and spring_boot_file|length > 0
